parameters:
    inwicast.plugin.mediacenter.class:                Claroline\InwicastPluginBundle\Entity\Mediacenter
    inwicast.plugin.repository.mediacenter.class:     Claroline\InwicastPluginBundle\Repository\MediacenterRepository
    inwicast.plugin.media.class:                      Claroline\InwicastPluginBundle\Entity\Media
    inwicast.plugin.repository.media.class:           Claroline\InwicastPluginBundle\Repository\MediaRepository
    inwicast.plugin.repository.mediacenteruser.class: Claroline\InwicastPluginBundle\Repository\MediacenterUserRepository

services:
    inwicast.plugin.repository.mediacenter:
        class:           "%inwicast.plugin.repository.mediacenter.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - "%inwicast.plugin.mediacenter.class%"

    inwicast.plugin.repository.media:
            class:           "%inwicast.plugin.repository.media.class%"
            factory_service: doctrine.orm.entity_manager
            factory_method:  getRepository
            arguments:
                - "%inwicast.plugin.media.class%"

    inwicast.plugin.repository.mediacenteruser:
            class: "%inwicast.plugin.repository.mediacenteruser.class%"
            arguments: ["@doctrine.dbal.connection_factory", "@claroline.config.platform_config_handler"]
