<?php

namespace Inwicast\ClarolinePluginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediacenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediacenterRepository extends EntityRepository
{
}
