<?php

namespace Claroline\InwicastPluginBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Claroline\InwicastPluginBundle\Entity\Media;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function findByWidget($widgetInstance)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('media')
            ->from('Claroline\InwicastPluginBundle\Entity\Media', 'media')
            ->where('media.widgetInstance = :widgetinstance')
            ->setParameter("widgetinstance", $widgetInstance);

        $result = $qb->getQuery()->getResult();

        if (sizeof($result) > 0) {
            return $result[0];
        } else {
            return $result;
        }
    }
}
